### ISSUE TITLE
Заказать еще

### ISSUE THREAD

**Issue by sofiiila** [sofiiila/bot-store#4]
проблема возникает, когда после прохождения полного цикла заполнения заявки , если пользователь нажимает "заказать еще" -оьтправляется сообщение на добавление тз, но дальше бот ломаается.
| Traceback (most recent call last):
bot_store_bot |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1063, in process_update
bot_store_bot |     await coroutine
bot_store_bot |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_conversationhandler.py", line 824, in handle_update
bot_store_bot |     new_state: object = await handler.handle_update(
bot_store_bot |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
bot_store_bot |     return await self.callback(update, context)
bot_store_bot |   File "/app/src/handlers/tz.py", line 27, in tz
bot_store_bot |     db_client.update(filter_query={
bot_store_bot |   File "/app/src/services/core.py", line 61, in update
bot_store_bot |     raise AttributeError("Ничего не обновилось")
bot_store_bot | AttributeError: Ничего не обновилось

**Comment by sofiiila** [comment]
будет исправлено в версии 0.0.2
